language: go

env:
  - CGO_ENABLED=1 GOOS=linux

go:
  #- 1.3
  #- 1.4
  #- 1.5
  - tip

#gobuild_args: -x -race -tags ci -a -installsuffix cgo -ldflags "-s -w -X 'main.version=$(cat VERSION)' -X 'main.build=$(git rev-parse --short HEAD)' -X 'main.buildDate=$(date --rfc-3339=seconds)'"
gobuild_args: -x -race -ldflags "-s -w -X 'main.version=1.0.0' -X 'main.build=1.1' -X 'main.buildDate=xxxx'"

#before_script:
#  - go vet ./...
