language: go

env:
  - CGO_ENABLED=1 GOOS=linux

go:
  #- 1.3
  #- 1.4
  #- 1.5
  - tip

#gobuild_args: -x -race -tags ci -a -installsuffix cgo -ldflags "-s -w -X 'main.version=$(cat VERSION)' -X 'main.build=$(git rev-parse --short HEAD)' -X 'main.buildDate=$(date --rfc-3339=seconds)'"

before_script:
  - go vet ./...


# https://docs.travis-ci.com/user/languages/go/
# https://docs.travis-ci.com/user/customizing-the-build/
# the complete lifecycle
#    before_install
#    install
#    before_script
#    script
#    after_success or after_failure
#    OPTIONAL before_deploy
#    OPTIONAL deploy
#    OPTIONAL after_deploy
#    after_script
